services:
  postgres:
    image: postgres:16-alpine
    container_name: db_gerenciador_restricoes
    restart: always
    environment:
      POSTGRES_DB: restricoes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
